"""Create NewModel

Revision ID: 377ba52c2e60
Revises: 8a9944e9033a
Create Date: 2024-01-30 19:00:16.964510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377ba52c2e60'
down_revision = '8a9944e9033a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
